name: moberasweb
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state management
  stacked: ^1.7.1
  stacked_hooks: ^0.1.2

  # navigation
  get: ^3.2.2
  auto_route: ^0.6.1
  stacked_services: ^0.4.4+3
  rxdart: ^0.24.1

  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  flutter_hooks: ^0.9.0
  observable_ish: ^2.1.4
  font_awesome_flutter: 8.8.1
  location: ^3.0.2

  # firebase INI
  cloud_functions: ^0.5.0
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.3+3
  firebase_messaging: ^6.0.16
  firebase_in_app_messaging: ^0.1.2
  firebase_performance: ^0.3.2
  firebase_remote_config: ^0.3.1
  firebase_storage: ^3.1.6
  apple_sign_in: 0.1.0

  google_fonts: ^1.1.0
  oktoast: ^2.3.2
  intl: ^0.16.1
  pedantic: ^1.9.0
  image_picker: ^0.6.7+1
  string_validator: ^0.1.4
  cached_network_image: ^2.2.0+1
  logger: ^0.9.1
  json_annotation: ^3.0.1
  flutter_platform_widgets: ^0.50.0
  awesome_dialog: ^1.1.2
  shared_preferences: ^0.5.7+3
  connectivity: ^0.4.8+6
  app_settings: ^4.0.0
  device_info: ^0.4.2+4
  path_provider: ^1.6.10
  quiver: ^2.1.3
  flare_flutter: ^2.0.3
  mask_text_input_formatter: ^1.0.6
  flutter_datetime_picker: ^1.3.8
  responsive_framework:
  pedometer: ^1.2.0
  video_player: ^0.10.11+1

dev_dependencies:
  mockito: ^4.1.1
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.0
  injectable_generator: ^0.4.1
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_min.png
    # - assets/flare/Teddy.flr2d
    # - assets/gif/gifActivity.gif
scripts:
  buildRunner: flutter pub run build_runner build --delete-conflicting-outputs
