name: moberasweb
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state management
  stacked: ^1.7.5
  stacked_hooks: ^0.1.3

  # navigation
  get: ^3.4.2
  auto_route: ^0.6.7
  stacked_services: ^0.5.1
  rxdart: ^0.24.1

  # inversion of control
  get_it: ^4.0.4
  injectable: ^1.0.2
  observable_ish: ^2.1.4
  font_awesome_flutter: ^8.8.1
  location: ^3.0.2

  # firebase INI
  cloud_functions: ^0.5.0
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_performance: ^0.3.2
  firebase_storage: ^3.1.6
  apple_sign_in: 0.1.0

  google_fonts: ^1.1.0
  image_picker: ^0.6.7+4
  string_validator: ^0.1.4
  cached_network_image: ^2.2.0+1
  logger: ^0.9.2
  json_annotation: ^3.0.1
  connectivity: ^0.4.8+6
  app_settings: ^4.0.0
  device_info: ^0.4.2+4
  path_provider: ^1.6.10
  quiver: ^2.1.3
  flare_flutter: ^2.0.3
  mask_text_input_formatter: ^1.0.7
  flutter_datetime_picker: ^1.3.8
  google_maps_flutter: ^0.5.29

dev_dependencies:
  mockito: ^4.1.1
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.7
  injectable_generator: ^1.0.3
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_min.png
    # - assets/flare/Teddy.flr2d
    # - assets/gif/gifActivity.gif
scripts:
  buildRunner: flutter pub run build_runner build --delete-conflicting-outputs
